(Gemfile) pin console gem version to 1.15.x
To resolve this error caused by the rspec-github gem:

    SyntaxError: /opt/hostedtoolcache/Ruby/2.7.2/x64/lib/ruby/gems/2.7.0/gems/console-1.16.2/lib/console/progress.rb:77: syntax error, unexpected ')'
                            @output.info(@subject, ...)
			                          ^