(docker-compose role) use docker-compose package
Instead of manual installation of `docker-compose` using pip.

To resolve this error:

    Error: 'pip3 --log /tmp/pip.log install     docker-compose==1.25.0' returned 1 instead of one of [0]
    Error: /Stage[main]/Python/Python::Pip[docker-compose]/Exec[pip_install_docker-compose]/returns: change from 'notrun' to ['0'] failed: 'pip3 --log /tmp/pip.log install     docker-compose==1.25.0' returned 1 instead of one of [0] (corrective)